"""Provided: the helpers of the notebook "break it on purpose" of Part 7.

You do not edit this file. It gives you greedy decoding with and without
n-gram speculation, the tools to quantize weights and a KV cache, a small
JSON automaton with token masks, and an int8 GEMV kernel.
"""

import math
import time

import torch
from transformers import DynamicCache


def stop_ids(model):
    stop = model.generation_config.eos_token_id
    return set(stop) if isinstance(stop, list) else {stop}


def ms_per_call(fn, iters=20):
    for _ in range(3):
        fn()
    torch.cuda.synchronize()
    start = time.perf_counter()
    for _ in range(iters):
        fn()
    torch.cuda.synchronize()
    return (time.perf_counter() - start) / iters * 1000


# ---------------------------------------------------------------- speculation

@torch.inference_mode()
def greedy(model, ids, max_tokens):
    """Plain greedy decode. Returns the new tokens."""
    device = ids.device
    stops = stop_ids(model)
    out = model(ids, use_cache=True)
    cache, generated = out.past_key_values, []
    token = int(out.logits[0, -1].argmax())
    while len(generated) < max_tokens and token not in stops:
        generated.append(token)
        out = model(torch.tensor([[token]], device=device), past_key_values=cache, use_cache=True)
        token = int(out.logits[0, -1].argmax())
    return generated


def ngram_propose(tokens, k, n=3):
    """Find the last earlier place where the last n tokens occurred, and
    propose the k tokens that followed it. Returns [] when there is none."""
    if len(tokens) < n:
        return []
    key = tokens[-n:]
    for start in range(len(tokens) - n - 1, -1, -1):
        if tokens[start:start + n] == key:
            return tokens[start + n:start + n + k]
    return []


@torch.inference_mode()
def speculative(model, ids, max_tokens, k=4, verify=None, n=3):
    """Greedy decode with n-gram drafts, checked in one forward pass.

    Returns the new tokens and a dict of statistics. `verify` can replace
    the acceptance rule: verify(draft, predicted) -> the tokens to keep.
    """
    device = ids.device
    stops = stop_ids(model)
    context = ids[0].tolist()
    out = model(ids, use_cache=True)
    cache = out.past_key_values
    token = int(out.logits[0, -1].argmax())
    generated, steps, proposed, accepted = [], 0, 0, 0
    while len(generated) < max_tokens and token not in stops:
        generated.append(token)
        draft = ngram_propose(context + generated, k, n)
        block = torch.tensor([[token] + draft], device=device)
        logits = model(block, past_key_values=cache, use_cache=True).logits[0]
        predicted = logits.argmax(-1).tolist()                          # the model's token after each input
        steps += 1
        proposed += len(draft)
        if verify is None:
            keep = []
            for d, p in zip(draft, predicted):
                if d != p:
                    break
                keep.append(d)
        else:
            keep = verify(draft, predicted)
        accepted += len(keep)
        cache.crop(len(context) + len(generated) + len(keep))           # drop the K and V of rejected drafts
        generated += keep
        token = predicted[len(keep)]                                    # the bonus token
        for t in keep:
            if t in stops:
                generated = generated[:generated.index(t)]
                token = t
                break
    stats = dict(steps=steps, proposed=proposed, accepted=accepted,
                 tokens_per_step=len(generated) / max(steps, 1))
    return generated[:max_tokens], stats


# ---------------------------------------------------------------- quantization

def quantize(weight, per_channel):
    """Symmetric int8. Returns the int8 values and the scale (one for the
    matrix, or one for each output row)."""
    w = weight.float()
    top = w.abs().amax(dim=1, keepdim=True) if per_channel else w.abs().max()
    scale = (top / 127).clamp(min=1e-12)
    return torch.round(w / scale).clamp(-127, 127).to(torch.int8), scale


def next_token_kl(model, prompts, tokenizer, reference):
    """The mean KL (nats) of the next-token distribution against `reference`,
    a list of log-probabilities from the same prompts."""
    device = next(model.parameters()).device
    total = 0.0
    with torch.inference_mode():
        for prompt, ref in zip(prompts, reference):
            ids = tokenizer(prompt, return_tensors='pt').input_ids.to(device)
            logp = model(ids).logits[0, -1].float().log_softmax(-1)
            total += (ref.exp() * (ref - logp)).sum().item()
    return total / len(prompts)


def log_probs(model, prompts, tokenizer):
    device = next(model.parameters()).device
    with torch.inference_mode():
        return [model(tokenizer(p, return_tensors='pt').input_ids.to(device)).logits[0, -1].float().log_softmax(-1)
                for p in prompts]


GEMV_INT8 = r"""
#include <ATen/cuda/CUDAContext.h>
#include <torch/extension.h>
#include <cuda_bf16.h>

// y[row] = scale[row] * sum_k w[row, k] * x[k]. One warp for each row. Each
// lane reads 16 int8 weights at once. The scale is applied at the end, to a
// register: the weight is never written back as bf16.
__global__ void gemv_int8(const int8_t* __restrict__ w, const float* __restrict__ scale,
                          const __nv_bfloat16* __restrict__ x, __nv_bfloat16* __restrict__ y,
                          int rows, int cols) {
  int row = blockIdx.x * (blockDim.x / 32) + threadIdx.x / 32;
  int lane = threadIdx.x % 32;
  if (row >= rows) return;
  const int4* w_row = reinterpret_cast<const int4*>(w + (long)row * cols);
  float sum = 0.f;
  for (int chunk = lane; chunk < cols / 16; chunk += 32) {
    int4 packed = w_row[chunk];
    const int8_t* q = reinterpret_cast<const int8_t*>(&packed);
    const __nv_bfloat16* xs = x + chunk * 16;
    #pragma unroll
    for (int i = 0; i < 16; ++i) sum += float(q[i]) * __bfloat162float(xs[i]);
  }
  for (int offset = 16; offset > 0; offset /= 2) sum += __shfl_down_sync(0xffffffff, sum, offset);
  if (lane == 0) y[row] = __float2bfloat16(sum * scale[row]);
}

void run(torch::Tensor w, torch::Tensor scale, torch::Tensor x, torch::Tensor y) {
  int rows = w.size(0), cols = w.size(1);
  gemv_int8<<<(rows + 7) / 8, 256, 0, at::cuda::getCurrentCUDAStream()>>>(
      w.data_ptr<int8_t>(), scale.data_ptr<float>(), (const __nv_bfloat16*)x.data_ptr(),
      (__nv_bfloat16*)y.data_ptr(), rows, cols);
}
PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) { m.def("run", &run); }
"""


# ---------------------------------------------------------------- guided decoding

class Automaton:
    """A character automaton for one JSON shape. A state is an int, or None
    when the text is no longer a valid prefix.

    'list':  {"skills": ["word", "word", ...]}   words of lowercase letters and spaces
    'enum':  {"color": "<one of the choices>"}
    """

    def __init__(self, kind, choices=()):
        self.kind, self.choices = kind, list(choices)
        self.head = '{"skills": [' if kind == 'list' else '{"color": "'

    # a state is (phase, position) packed into a string key
    def start(self):
        return ('head', 0)

    def step(self, state, ch):
        phase, pos = state
        if phase == 'head':
            if ch != self.head[pos]:
                return None
            if pos + 1 < len(self.head):
                return ('head', pos + 1)
            return ('item', 0) if self.kind == 'list' else ('choice', '')
        if self.kind == 'enum':
            if phase == 'choice':
                text = pos + ch
                if ch == '"' and pos in self.choices:
                    return ('close', 0)
                if any(c.startswith(text) for c in self.choices):
                    return ('choice', text)
                return None
            if phase == 'close':
                return ('done', 0) if ch == '}' else None
            return None
        # the list
        if phase == 'item':                      # expect a string or the end of the list
            if ch == '"':
                return ('word', 0)
            if ch == ']':
                return ('close', 0)
            return None
        if phase == 'word':                      # pos: 0 before the first letter, then 1
            if ch.islower() or ch == ' ':
                return ('word', 1)
            if ch == '"' and pos > 0:
                return ('after', 0)
            return None
        if phase == 'after':
            if ch == ',':
                return ('comma', 0)
            if ch == ']':
                return ('close', 0)
            return None
        if phase == 'comma':
            return ('next', 0) if ch == ' ' else None
        if phase == 'next':                      # after ", " only a string may follow
            return ('word', 0) if ch == '"' else None
        if phase == 'close':
            return ('done', 0) if ch == '}' else None
        return None

    def walk(self, state, text):
        for ch in text:
            state = self.step(state, ch)
            if state is None:
                return None
        return state

    def finished(self, state):
        return state is not None and state[0] == 'done'


def token_texts(tokenizer):
    """The text of each token id. A token that is part of a character is ''."""
    texts = []
    for i in range(len(tokenizer)):
        text = tokenizer.decode([i])
        texts.append('' if '�' in text else text)
    return texts


def build_mask(automaton, state, texts, first_char_only=False):
    """A bool tensor over the vocabulary: True where the token may come next."""
    allowed = torch.zeros(len(texts), dtype=torch.bool)
    for i, text in enumerate(texts):
        if not text:
            continue
        probe = text[:1] if first_char_only else text
        if automaton.walk(state, probe) is not None:
            allowed[i] = True
    return allowed


# ---------------------------------------------------------------- tensor parallel

def allreduce_latency_us(numel, iters=200):
    """The time of one all-reduce of `numel` floats between 2 CPU processes
    (gloo), in microseconds. It runs in a subprocess."""
    import subprocess, sys, textwrap
    script = textwrap.dedent(f'''
        import os, time, torch, torch.distributed as dist, torch.multiprocessing as mp
        def work(rank):
            os.environ["MASTER_ADDR"] = "127.0.0.1"; os.environ["MASTER_PORT"] = "29517"
            dist.init_process_group("gloo", rank=rank, world_size=2)
            x = torch.ones({numel})
            for _ in range(20): dist.all_reduce(x)
            dist.barrier(); start = time.perf_counter()
            for _ in range({iters}): dist.all_reduce(x)
            took = (time.perf_counter() - start) / {iters} * 1e6
            if rank == 0: print(took)
            dist.destroy_process_group()
        if __name__ == "__main__":
            mp.spawn(work, nprocs=2)
    ''')
    import tempfile, os
    with tempfile.NamedTemporaryFile('w', suffix='.py', delete=False) as f:
        f.write(script)                                       # spawn needs a real file
    try:
        result = subprocess.run([sys.executable, f.name], capture_output=True, text=True)
    finally:
        os.unlink(f.name)
    if result.returncode:
        raise RuntimeError(result.stderr[-2000:])
    return float(result.stdout.strip().split()[-1])
