"""Provided: the helpers of the notebook "break it on purpose" of Part 5.

You do not edit this file. It gives you a decode step captured as a CUDA
graph, a correct sampler, a correct incremental detokenizer, and a timer.
"""

import time

import torch
from transformers import StaticCache


# ---------------------------------------------------------------- graphs

class Graphed:
    """A decode step of an HF model, captured for one batch size.

    The static inputs are `ids` (batch, 1) and `position` (1,). The graph
    reads them from their addresses, and writes `logits` (batch, vocab).

    `position` sets the rotary position. The static cache of HF writes each
    new K and V at its own counter, which every call advances, also inside
    the graph. In a normal decode the two agree. Do not call a step more
    times than the cache has slots.
    """

    def __init__(self, model, batch, max_len=512):
        self.model, self.batch = model, batch
        device = next(model.parameters()).device
        self.cache = StaticCache(config=model.config, max_cache_len=max_len)
        self.ids = torch.zeros(batch, 1, dtype=torch.long, device=device)
        self.position = torch.zeros(1, dtype=torch.long, device=device)
        with torch.inference_mode():
            model(torch.zeros(batch, 4, dtype=torch.long, device=device), past_key_values=self.cache,
                  cache_position=torch.arange(4, device=device))          # allocate the cache
            stream = torch.cuda.Stream()
            stream.wait_stream(torch.cuda.current_stream())
            with torch.cuda.stream(stream):
                for _ in range(2):
                    self._step()
            torch.cuda.current_stream().wait_stream(stream)
            self.graph = torch.cuda.CUDAGraph()
            with torch.cuda.graph(self.graph):
                self.logits = self._step()

    def _step(self):
        return self.model(self.ids, past_key_values=self.cache, cache_position=self.position,
                          use_cache=True).logits[:, -1]

    @torch.inference_mode()
    def prefill(self, ids):
        """An eager prefill into the static cache. Returns the next tokens."""
        self.cache.reset()
        out = self.model(ids, past_key_values=self.cache, use_cache=True,
                         cache_position=torch.arange(ids.shape[1], device=ids.device))
        return out.logits[:, -1].argmax(-1)

    @torch.inference_mode()
    def eager_step(self):
        return self._step()


@torch.inference_mode()
def greedy_graphed(g, ids, max_tokens):
    """The correct loop: copy the new token INTO the static buffer, replay."""
    token = g.prefill(ids)
    out = [token.tolist()]
    for i in range(max_tokens - 1):
        g.ids.copy_(token[:, None])
        g.position.fill_(ids.shape[1] + i)
        g.graph.replay()
        token = g.logits.argmax(-1)
        out.append(token.tolist())
    return [list(row) for row in zip(*out)]


@torch.inference_mode()
def greedy_eager_static(g, ids, max_tokens):
    """The same loop without the graph: the reference for a graph."""
    token = g.prefill(ids)
    out = [token.tolist()]
    for i in range(max_tokens - 1):
        g.ids.copy_(token[:, None])
        g.position.fill_(ids.shape[1] + i)
        token = g.eager_step().argmax(-1)
        out.append(token.tolist())
    return [list(row) for row in zip(*out)]


def ms_per_call(fn, iters=30):
    for _ in range(3):
        fn()
    torch.cuda.synchronize()
    start = time.perf_counter()
    for _ in range(iters):
        fn()
    torch.cuda.synchronize()
    return (time.perf_counter() - start) / iters * 1000


# ---------------------------------------------------------------- sampling

def sample(logits, temperature, top_p, generators):
    """A correct sampler: one vectorized pass over the batch.

    temperature and top_p: tensors of shape (batch,). generators: one
    torch.Generator for each row, so each row draws its own random numbers.
    """
    probs = torch.softmax(logits.float() / temperature[:, None], dim=-1)
    sorted_probs, order = probs.sort(dim=-1, descending=True)
    before = sorted_probs.cumsum(-1) - sorted_probs                     # mass BEFORE each token
    sorted_probs = sorted_probs.masked_fill(before > top_p[:, None], 0.0)
    probs = torch.zeros_like(probs).scatter(-1, order, sorted_probs)
    noise = torch.stack([torch.empty(probs.shape[-1], device=probs.device).exponential_(generator=g)
                         for g in generators])
    return (probs / noise).argmax(-1)


def sample_top_candidates(logits, temperature, top_p, generators, candidates=1024):
    """The same sampler, with the sort limited to the top `candidates` tokens.

    It is exact when those tokens already hold the top-p mass of each row.
    The second result says, for each row, whether that was true.
    """
    probs = torch.softmax(logits.float() / temperature[:, None], dim=-1)
    top_probs, order = probs.topk(candidates, dim=-1)                   # sorted, descending
    before = top_probs.cumsum(-1) - top_probs
    exact = top_probs.sum(-1) >= top_p
    top_probs = top_probs.masked_fill(before > top_p[:, None], 0.0)
    noise = torch.stack([torch.empty(candidates, device=probs.device).exponential_(generator=g)
                         for g in generators])
    return order.gather(-1, (top_probs / noise).argmax(-1, keepdim=True))[:, 0], exact


def target(logits, temperature=1.0, top_k=0, top_p=1.0, penalty=1.0, seen=()):
    """The exact distribution that one row must sample from."""
    logits = logits.float().clone()
    for token in set(seen):
        logits[token] = logits[token] / penalty if logits[token] > 0 else logits[token] * penalty
    probs = torch.softmax(logits / temperature, -1)
    if top_k:
        kth = probs.topk(top_k).values[-1]
        probs = probs.masked_fill(probs < kth, 0.0)
    sorted_probs, order = probs.sort(descending=True)
    before = sorted_probs.cumsum(-1) - sorted_probs
    sorted_probs = sorted_probs.masked_fill(before > top_p, 0.0)
    probs = torch.zeros_like(probs).scatter(-1, order, sorted_probs)
    return probs / probs.sum()


def frequencies(sampler, logits, params, draws=20_000, seed=0):
    """Call `sampler(logits, params, generator)` many times. Returns the
    frequency of each token for each row: a tensor (batch, vocab)."""
    generator = torch.Generator(device=logits.device).manual_seed(seed)
    counts = torch.zeros_like(logits, dtype=torch.float)
    rows = torch.arange(logits.shape[0], device=logits.device)
    for _ in range(draws):
        tokens = sampler(logits, params, generator)
        counts[rows, tokens] += 1
    return counts / draws


# ---------------------------------------------------------------- detokenization

class Detokenizer:
    """A correct incremental detokenizer.

    It decodes a window of the recent tokens, and it emits only the new text.
    It holds back text that ends in an incomplete character.
    """

    def __init__(self, tokenizer):
        self.tokenizer, self.tokens = tokenizer, []
        self.prefix = self.read = 0          # the window starts at prefix, and text up to read is out

    def push(self, token):
        self.tokens.append(token)
        before = self.tokenizer.decode(self.tokens[self.prefix:self.read])
        after = self.tokenizer.decode(self.tokens[self.prefix:])
        if after.endswith('�') or len(after) <= len(before):
            return ''
        self.prefix, self.read = self.read, len(self.tokens)
        return after[len(before):]
