"""Provided: the helpers of the notebook "break it on purpose" of Part 3.

You do not edit this file. It gives you a correct block allocator, a paged KV
cache on plain tensors, a checker for the invariants of a pool, and the tools
to build a model cache from blocks of K and V.
"""

import math
import random

import torch
from transformers import DynamicCache

BLOCK = 16


class Allocator:
    """A correct pool of blocks with reference counts.

    allocate(seq, n)  a new sequence of n tokens
    append(seq)       one more token
    fork(parent, child)  the child shares every block of the parent
    free(seq)         the sequence ends
    """

    def __init__(self, num_blocks):
        self.total = num_blocks
        self.free_list = list(range(num_blocks - 1, -1, -1))
        self.refs = [0] * num_blocks
        self.tables, self.lengths = {}, {}

    def _take(self):
        block = self.free_list.pop()
        self.refs[block] = 1
        return block

    def _release(self, block):
        self.refs[block] -= 1
        if self.refs[block] == 0:
            self.free_list.append(block)

    def allocate(self, seq, num_tokens):
        self.tables[seq] = [self._take() for _ in range(math.ceil(num_tokens / BLOCK))]
        self.lengths[seq] = num_tokens

    def append(self, seq):
        position = self.lengths[seq]
        if position // BLOCK == len(self.tables[seq]):
            self.tables[seq].append(self._take())
        self.lengths[seq] += 1

    def fork(self, parent, child):
        self.tables[child] = list(self.tables[parent])
        self.lengths[child] = self.lengths[parent]
        for block in self.tables[child]:
            self.refs[block] += 1

    def free(self, seq):
        for block in self.tables.pop(seq):
            self._release(block)
        del self.lengths[seq]

    def num_free(self):
        return len(self.free_list)


def check(pool):
    """The invariants of a pool. Returns a list of the violations."""
    problems = []
    for seq, table in pool.tables.items():
        need = math.ceil(pool.lengths[seq] / BLOCK)
        if len(table) < need:
            problems.append(f'seq {seq}: {pool.lengths[seq]} tokens in {len(table)} blocks')
    owners = {}
    for seq, table in pool.tables.items():
        for block in table:
            owners.setdefault(block, []).append(seq)
    for block, seqs in owners.items():
        if len(seqs) > 1 and pool.refs[block] < len(seqs):
            problems.append(f'block {block}: in {len(seqs)} tables, refcount {pool.refs[block]}')
        if block in pool.free_list:
            problems.append(f'block {block}: in a table AND on the free list')
    used = len(owners)
    if used + pool.num_free() != pool.total:
        problems.append(f'{pool.total - used - pool.num_free()} blocks are neither used nor free')
    return problems


def workload(pool, sequences=200, forks=False, seed=0, lengths=(1, 200), steps=40):
    """Random sequences: start, grow, fork, end. Returns the violations seen."""
    rng = random.Random(seed)
    live, next_id, seen = [], 0, []
    for _ in range(sequences):
        pool.allocate(next_id, rng.randint(*lengths))
        live.append(next_id)
        next_id += 1
        if forks and rng.random() < 0.3:
            pool.fork(live[-1], next_id)
            live.append(next_id)
            next_id += 1
        for _ in range(rng.randint(0, steps)):
            pool.append(rng.choice(live))
        if len(live) > 8:
            pool.free(live.pop(rng.randrange(len(live))))
        seen += check(pool)
    for seq in live:
        pool.free(seq)
    seen += check(pool)
    return seen


# ---------------------------------------------------------------- a paged cache on tensors

def new_cache(num_blocks, heads=8, head_dim=128, device='cuda'):
    """K and V of one layer: (num_blocks, BLOCK, heads, head_dim) each."""
    shape = (num_blocks, BLOCK, heads, head_dim)
    return torch.zeros(shape, device=device), torch.zeros(shape, device=device)


def write(cache, table, position, k, v):
    """Write the K and V of ONE token at `position` through the block table."""
    block = table[position // BLOCK]
    cache[0][block, position % BLOCK] = k
    cache[1][block, position % BLOCK] = v


def gather(cache, table, length):
    """The K and V of the first `length` positions, in order."""
    blocks = torch.as_tensor(table, device=cache[0].device)
    k = cache[0][blocks].flatten(0, 1)[:length]
    v = cache[1][blocks].flatten(0, 1)[:length]
    return k, v


def attend(q, k, v):
    """One query (heads, dim) against keys (length, heads, dim)."""
    scores = torch.einsum('hd,lhd->hl', q, k) / math.sqrt(q.shape[-1])
    return torch.einsum('hl,lhd->hd', torch.softmax(scores, -1), v)


# ---------------------------------------------------------------- blocks of a real model

@torch.inference_mode()
def model_kv(model, ids):
    """The K and V of every layer for a prompt: a list of (k, v), each of
    shape (1, kv_heads, length, head_dim)."""
    cache = DynamicCache()
    model(ids, past_key_values=cache, use_cache=True, logits_to_keep=1)
    return [(layer.keys, layer.values) for layer in cache.layers]


def cache_from(pieces):
    """A DynamicCache from a list of per-layer (k, v) pieces, joined along the
    positions. Each piece is a list over the layers."""
    cache = DynamicCache()
    for layer in range(len(pieces[0])):
        k = torch.cat([piece[layer][0] for piece in pieces], dim=2)
        v = torch.cat([piece[layer][1] for piece in pieces], dim=2)
        cache.update(k, v, layer)
    return cache


def slice_kv(kv, start, end):
    return [(k[:, :, start:end], v[:, :, start:end]) for k, v in kv]


@torch.inference_mode()
def continue_greedy(model, cache, last_token, max_tokens, stop_ids=()):
    """Greedy decode from a cache that holds every token before last_token."""
    device = next(model.parameters()).device
    token, generated = last_token, []
    for _ in range(max_tokens):
        out = model(torch.tensor([[token]], device=device), past_key_values=cache, use_cache=True)
        token = int(out.logits[0, -1].argmax())
        if token in stop_ids:
            break
        generated.append(token)
    return generated
