"""Provided: the helpers of the notebook "break it on purpose" of Part 2.

You do not edit this file. It gives you a correct batched greedy loop, a
timer for one decode step, and a small simulation of a server.
"""

import random
import time

import torch
from transformers import DynamicCache


def stop_ids(model):
    stop = model.generation_config.eos_token_id
    return set(stop) if isinstance(stop, list) else {stop}


@torch.inference_mode()
def greedy_alone(model, tokenizer, prompt, max_tokens):
    """One prompt, no padding: the reference for a row of a batch."""
    device = next(model.parameters()).device
    ids = tokenizer(prompt, return_tensors='pt').input_ids.to(device)
    stops = stop_ids(model)
    out = model(ids, use_cache=True)
    cache, generated = out.past_key_values, []
    next_token = int(out.logits[0, -1].argmax())
    for _ in range(max_tokens):
        if next_token in stops:
            break
        generated.append(next_token)
        out = model(torch.tensor([[next_token]], device=device), past_key_values=cache, use_cache=True)
        cache = out.past_key_values
        next_token = int(out.logits[0, -1].argmax())
    return generated


@torch.inference_mode()
def batched_greedy(model, tokenizer, prompts, max_tokens):
    """A correct static batch: left padding, the mask in every step, and a
    stop for each row. Returns one list of token ids for each prompt."""
    device = next(model.parameters()).device
    tokenizer.padding_side = 'left'
    batch = tokenizer(prompts, return_tensors='pt', padding=True).to(device)
    mask = batch.attention_mask
    stops = stop_ids(model)
    out = model(batch.input_ids, attention_mask=mask, use_cache=True)
    cache = out.past_key_values
    next_tokens = out.logits[:, -1].argmax(-1)
    generated = [[] for _ in prompts]
    done = [False] * len(prompts)
    for _ in range(max_tokens):
        for row, token in enumerate(next_tokens.tolist()):
            if not done[row]:
                if token in stops:
                    done[row] = True
                else:
                    generated[row].append(token)
        if all(done):
            break
        mask = torch.cat([mask, mask.new_ones(len(prompts), 1)], dim=1)
        out = model(next_tokens[:, None], attention_mask=mask, past_key_values=cache, use_cache=True)
        cache = out.past_key_values
        next_tokens = out.logits[:, -1].argmax(-1)
    return generated


def first_difference(generated, expected):
    for position, (got, want) in enumerate(zip(generated, expected)):
        if got != want:
            return position
    if len(generated) != len(expected):
        return min(len(generated), len(expected))
    return None


@torch.inference_mode()
def decode_step_ms(model, batch, context, iters=10):
    """The time of one decode step for `batch` sequences that each hold
    `context` tokens in the cache."""
    device = next(model.parameters()).device
    cache = DynamicCache()
    model(torch.randint(0, 1000, (batch, context), device=device), past_key_values=cache,
          use_cache=True, logits_to_keep=1)
    token = torch.randint(0, 1000, (batch, 1), device=device)
    times = []
    for _ in range(iters + 2):
        torch.cuda.synchronize()
        start = time.perf_counter()
        model(token, past_key_values=cache, use_cache=True)
        torch.cuda.synchronize()
        times.append((time.perf_counter() - start) * 1000)
        cache.crop(context)                                  # keep the context constant
    del cache
    torch.cuda.empty_cache()
    return sorted(times[2:])[len(times[2:]) // 2]


def serve(requests, slots, step_ms, evict_on_stop=True):
    """A continuous-batching server, simulated one step at a time.

    requests: a list of (arrival_s, answer_tokens, max_tokens). A request
    decodes one token each step. It stops at its answer length, which is the
    step where the model emits the stop token. With evict_on_stop=False the
    server removes it only at max_tokens.
    Returns the finish time and the first-token time of each request.
    """
    pending = sorted(range(len(requests)), key=lambda r: requests[r][0])
    running, clock, cursor = [], 0.0, 0
    decoded = [0] * len(requests)
    first, finish = [None] * len(requests), [None] * len(requests)
    useful = total = 0
    while cursor < len(pending) or running:
        while cursor < len(pending) and len(running) < slots and requests[pending[cursor]][0] <= clock:
            running.append(pending[cursor])
            cursor += 1
        if not running:
            clock = requests[pending[cursor]][0]
            continue
        clock += step_ms / 1000
        for r in running:
            decoded[r] += 1
            total += 1
            if decoded[r] <= requests[r][1]:
                useful += 1
            if first[r] is None:
                first[r] = clock
            if decoded[r] == requests[r][1]:
                finish[r] = clock
        limit = (lambda r: decoded[r] >= requests[r][1]) if evict_on_stop else (lambda r: decoded[r] >= requests[r][2])
        running = [r for r in running if not limit(r)]
    return {'first': first, 'finish': finish, 'end': clock, 'useful': useful, 'total': total}


def poisson_arrivals(rate, seconds, seed=0):
    rng = random.Random(seed)
    t, times = 0.0, []
    while True:
        t += rng.expovariate(rate)
        if t > seconds:
            return times
        times.append(t)
