"""Provided: the helpers of the notebook "break it on purpose" of Part 4.

You do not edit this file. It gives you a small scheduler that runs one step
at a time, with a pool of blocks, a token budget, preemption by recompute,
and a record of what happened to each request. It computes no tensors: the
faults of this Part live in the policy.
"""

import math
import time
from collections import deque

import torch

BLOCK = 16


class Request:
    def __init__(self, rid, arrival, prompt, output):
        self.id, self.arrival, self.prompt, self.output = rid, arrival, prompt, output
        self.computed = 0          # tokens whose K and V are in the cache
        self.generated = 0         # output tokens so far
        self.blocks = 0
        self.preemptions = 0
        self.first_token = self.finish = None
        self.gaps = []             # the time between two output tokens
        self.last_token = None

    def pending(self):
        """Tokens to compute before the next output token."""
        return self.prompt + self.generated - self.computed


class Scheduler:
    """One rule for every case: give pending tokens to the running requests
    until the budget runs out, decodes first, then admit from the queue.

    admission: 'prompt' admits when the free blocks cover the first chunk.
               'final'  admits only when the blocks cover the final length of
                        every running request and of the new one.
    victim:    'last_admitted' preempts the request that joined the running
               set last. 'latest_arrival' preempts the request that arrived
               last, and the request itself when it is the latest.
    """

    def __init__(self, num_blocks, budget=512, max_seqs=256, admission='prompt',
                 preempted_to_front=True, victim='latest_arrival'):
        self.free = num_blocks
        self.total = num_blocks
        self.budget, self.max_seqs = budget, max_seqs
        self.admission, self.preempted_to_front = admission, preempted_to_front
        self.victim_rule = victim
        self.waiting, self.running = deque(), []
        self.preemptions = 0

    # the blocks
    def _grow(self, request, tokens):
        need = math.ceil((request.computed + tokens) / BLOCK) - request.blocks
        if need <= 0:
            return True
        if need > self.free:
            return False
        self.free -= need
        request.blocks += need
        return True

    def _release(self, request):
        self.free += request.blocks
        request.blocks = 0

    def preempt(self, victim):
        self._release(victim)
        victim.computed = 0                     # recompute: the K and V are gone
        victim.preemptions += 1
        self.preemptions += 1
        self.running.remove(victim)
        if self.preempted_to_front:
            self.waiting.appendleft(victim)
        else:
            self.waiting.append(victim)

    def _victim(self, request):
        """The request to preempt so that `request` can grow, or None."""
        if self.victim_rule == 'last_admitted':
            victim = self.running[-1]
        else:
            victim = max(self.running, key=lambda r: (r.arrival, r.id))
        return None if victim is request else victim

    def _final_blocks(self, request):
        return math.ceil((request.prompt + request.output) / BLOCK)

    def _can_admit(self, request, chunk):
        if len(self.running) >= self.max_seqs:
            return False
        if self.admission == 'final':
            reserved = sum(self._final_blocks(r) - r.blocks for r in self.running)
            return self._final_blocks(request) <= self.free - reserved
        return math.ceil(chunk / BLOCK) <= self.free

    def schedule(self):
        """Returns the plan of one step: a list of (request, tokens)."""
        plan, used = [], 0
        for request in sorted(self.running, key=lambda r: r.pending()):   # decodes first
            if used >= self.budget:
                break
            if request not in self.running:                               # preempted in this step
                continue
            tokens = min(request.pending(), self.budget - used)
            grown = self._grow(request, tokens)
            while not grown and self._victim(request) is not None:
                victim = self._victim(request)
                self.preempt(victim)
                used -= sum(t for r, t in plan if r is victim)
                plan = [(r, t) for r, t in plan if r is not victim]
                grown = self._grow(request, tokens)
            if not grown:
                self.preempt(request)
                continue
            plan.append((request, tokens))
            used += tokens
        while self.waiting and used < self.budget:
            request = self.waiting[0]
            chunk = min(request.pending(), self.budget - used)
            if not self._can_admit(request, chunk) or not self._grow(request, chunk):
                break
            self.waiting.popleft()
            self.running.append(request)
            plan.append((request, chunk))
            used += chunk
        return plan

    def apply(self, plan, clock):
        """The step ran. Advance each request, and remove the finished ones."""
        for request, tokens in plan:
            request.computed += tokens
            if request.pending() == 0:
                request.generated += 1
                if request.first_token is None:
                    request.first_token = clock
                else:
                    request.gaps.append(clock - request.last_token)
                request.last_token = clock
                if request.generated == request.output:
                    request.finish = clock
                    self._release(request)
                    self.running.remove(request)


def step_ms(tokens):
    """A step-time model for Qwen3-1.7B on a laptop GPU: a weight read of
    about 13 ms, plus about 0.07 ms for each token in the step."""
    return 13.0 + 0.07 * tokens


def run(scheduler, requests, max_seconds=36_000, time_fn=step_ms):
    """Run the requests to the end. Returns the requests and the step log."""
    pending = deque(sorted(requests, key=lambda r: r.arrival))
    clock, log = 0.0, []
    while (pending or scheduler.waiting or scheduler.running) and clock < max_seconds:
        while pending and pending[0].arrival <= clock:
            scheduler.waiting.append(pending.popleft())
        plan = scheduler.schedule()
        if not plan:
            clock = pending[0].arrival if pending else clock + 0.01
            continue
        tokens = sum(t for _, t in plan)
        clock += time_fn(tokens) / 1000
        scheduler.apply(plan, clock)
        log.append((clock, tokens, len(plan)))
    return requests, log


# ---------------------------------------------------------------- GPU timing

@torch.inference_mode()
def prefill_ms(model, tokens, chunk=None, context=0):
    """The time of a prefill of `tokens` tokens after `context` cached tokens.
    With `chunk`, the prefill runs in chunks, and the result is the list of
    the chunk times."""
    from transformers import DynamicCache
    device = next(model.parameters()).device
    cache = DynamicCache()
    if context:
        model(torch.randint(0, 1000, (1, context), device=device), past_key_values=cache,
              use_cache=True, logits_to_keep=1)
    ids = torch.randint(0, 1000, (1, tokens), device=device)
    sizes = [tokens] if chunk is None else [min(chunk, tokens - s) for s in range(0, tokens, chunk)]
    times, start = [], 0
    for size in sizes:
        torch.cuda.synchronize()
        t0 = time.perf_counter()
        model(ids[:, start:start + size], past_key_values=cache, use_cache=True, logits_to_keep=1)
        torch.cuda.synchronize()
        times.append((time.perf_counter() - t0) * 1000)
        start += size
    del cache
    torch.cuda.empty_cache()
    return times[0] if chunk is None else times
