"""Provided: the helpers of the notebook "break it on purpose" of Part 8.

You do not edit this file. It gives you the floor of a step, a small pool of
blocks with preemption, and a timer.
"""

import math
import time

import torch

BLOCK = 16


def ms_per_call(fn, iters=20):
    for _ in range(3):
        fn()
    torch.cuda.synchronize()
    start = time.perf_counter()
    for _ in range(iters):
        fn()
    torch.cuda.synchronize()
    return (time.perf_counter() - start) / iters * 1000


def floor_ms(computed_tokens, context_tokens, weight_bytes, params, kv_per_token, bandwidth, flops):
    """The roofline floor of one step, from stage 28.

    computed_tokens: the tokens that the step runs through the model.
    context_tokens:  the tokens of KV cache that the step reads.
    """
    weights = max(weight_bytes / bandwidth, 2 * params * computed_tokens / flops)
    kv = context_tokens * kv_per_token / bandwidth
    return (weights + kv) * 1000


class Pool:
    """A pool of blocks. Each sequence holds a list of blocks."""

    def __init__(self, num_blocks):
        self.total = num_blocks
        self.free_list = list(range(num_blocks))
        self.tables = {}

    def grow(self, seq, tokens):
        table = self.tables.setdefault(seq, [])
        while len(table) * BLOCK < tokens:
            table.append(self.free_list.pop())

    def release(self, seq):
        self.free_list += self.tables.pop(seq)

    def num_free(self):
        return len(self.free_list)
