"""Provided: the CUDA build plumbing. You do not edit this file.

`torch.utils.cpp_extension.load()` compiles a .cu file into a Python
extension module at first call, then caches it keyed on the source text. So
the loop is: edit the .cu, run the checks, and the rebuild happens for you.
The first build of a kernel costs 20-40 seconds. Every build after that is
free until you change the source.

What this module adds on top of `load()`:

  - the right -gencode for THIS card, read from the device itself
  - a build cache inside the repo (.cudacache/) instead of ~/.cache
  - ninja on PATH, which `./vc` does not otherwise arrange
  - a compile error that reads like a compile error

No --use_fast_math. It would buy a few percent and change the numerics of
expf, and the stage tolerances are 1e-3. Accuracy is a decision you should
make on purpose, not inherit from a build flag.
"""

import functools
import os
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / ".cudacache"

# -lineinfo costs nothing and makes ncu, compute-sanitizer and cuda-gdb point
# at your source lines instead of at PTX addresses.
# --ptxas-options=-v prints registers and shared memory per kernel, which is
# the input to every occupancy argument in stage 08c.
CFLAGS = ["-O3", "-lineinfo", "--ptxas-options=-v"]


def arch_flags():
    """The -gencode for the GPU in this machine, not a guess."""
    import torch

    major, minor = torch.cuda.get_device_capability()
    sm = f"{major}{minor}"
    return [f"-gencode=arch=compute_{sm},code=sm_{sm}"]


def _ninja_on_path():
    """`./vc` runs .venv/bin/python directly and never activates the venv, so
    the venv's bin/ is not on PATH and torch cannot find ninja. Put it there."""
    bindir = str(Path(sys.executable).parent)
    parts = os.environ.get("PATH", "").split(os.pathsep)
    if bindir not in parts:
        os.environ["PATH"] = os.pathsep.join([bindir] + parts)


@functools.lru_cache(maxsize=None)
def build(name, *sources, extra_cuda_cflags=()):
    """Compile sources into an extension module and return it.

        mod = build("s08_paged_attn", "app/cuda/s08_paged_attn.cu")
        mod.paged_attn(...)

    Paths are relative to the repo root. The result is memoized, so calling
    this on every kernel invocation is free after the first one.

    Call it INSIDE your wrapper function, not at import time. A kernel that
    does not compile should fail the check that uses it, not stop pytest from
    collecting the whole stage.
    """
    from torch.utils.cpp_extension import load

    _ninja_on_path()
    CACHE.mkdir(exist_ok=True)
    build_dir = CACHE / name
    build_dir.mkdir(exist_ok=True)

    paths = [str(ROOT / s) for s in sources]
    missing = [p for p in paths if not Path(p).exists()]
    if missing:
        raise FileNotFoundError(f"no such CUDA source: {', '.join(missing)}")

    _clear_stale_lock(build_dir)

    try:
        return load(
            name=name,
            sources=paths,
            build_directory=str(build_dir),
            extra_cuda_cflags=CFLAGS + arch_flags() + list(extra_cuda_cflags),
            verbose=bool(os.environ.get("VC_CUDA_VERBOSE")),
        )
    except Exception as e:
        raise RuntimeError(
            f"nvcc could not build {name} from {', '.join(sources)}.\n"
            f"Run it again with VC_CUDA_VERBOSE=1 to see the compiler output.\n"
            f"{e}"
        ) from None


# torch serialises builds of one extension with a lock file, and waits for it
# by polling, forever, silently. Interrupt a first compile -- Ctrl-C, a killed
# test run, a closed notebook -- and the file outlives the process that made
# it, and every run after that hangs with no output at all.
#
# There is only ever one build of one extension in this repo, so a lock older
# than a generous compile is certainly stale.
STALE_LOCK_SECONDS = 600


def _clear_stale_lock(build_dir):
    lock = Path(build_dir) / "lock"
    try:
        age = time.time() - lock.stat().st_mtime
    except FileNotFoundError:
        return
    if age > STALE_LOCK_SECONDS:
        print(f"cudalib: clearing a stale build lock in {build_dir} "
              f"({age / 60:.0f} minutes old). An earlier build was "
              f"interrupted.", file=sys.stderr)
        lock.unlink(missing_ok=True)
        (Path(build_dir) / ".ninja_lock").unlink(missing_ok=True)


def build_source(name, source):
    """Compile a CUDA source STRING and return the module.

    The stage files are real .cu files, because that is how you write a
    kernel you intend to keep. In a notebook, where a kernel is three lines
    and the point is to see one number move, a string is friendlier. The
    source is written into the build cache and compiled exactly as a file
    would be, so the two paths behave the same.
    """
    CACHE.mkdir(exist_ok=True)
    src = CACHE / f"{name}.cu"
    if not src.exists() or src.read_text() != source:
        src.write_text(source)
    return build(name, str(src))


def module_path(name):
    """The .so that build() produced, for cuobjdump to read."""
    return CACHE / name / f"{name}.so"
