"""Provided: the CUDA build plumbing. You do not edit this file.

`torch.utils.cpp_extension.load()` compiles a .cu file into a Python
extension module at the first call. Then it keeps the result, with the
source text as the key. So the loop is: edit the .cu, run the checks, and
the build occurs again. The first build of a kernel costs 20 to 40 seconds.
Every build after that is free until you change the source.

What this module adds to `load()`:

  - the correct -gencode for THIS card, read from the device
  - a build cache inside the repo (.cudacache/), not in ~/.cache
  - ninja on PATH, which `./vc` does not otherwise supply
  - a compile error that reads like a compile error

No --use_fast_math. It gives a few percent and changes the numerics of
expf, and the stage tolerances are 1e-3. Accuracy is a decision to make on
purpose, not a result of a build flag.
"""

import functools
import os
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / ".cudacache"

# -lineinfo costs nothing, and makes ncu, compute-sanitizer and cuda-gdb show
# your source lines, not PTX addresses.
# --ptxas-options=-v prints the registers and shared memory of each kernel.
# Every occupancy argument of stage 08c uses them.
CFLAGS = ["-O3", "-lineinfo", "--ptxas-options=-v"]


def arch_flags():
    """The -gencode for the GPU in this machine, not a guess."""
    import torch

    major, minor = torch.cuda.get_device_capability()
    architecture = f"{major}{minor}"
    return [f"-gencode=arch=compute_{architecture},code=sm_{architecture}"]


def _ninja_on_path():
    """`./vc` runs .venv/bin/python directly and never activates the venv.
    So the bin/ of the venv is not on PATH, and torch cannot find ninja. Put
    it there."""
    venv_bin = str(Path(sys.executable).parent)
    path_entries = os.environ.get("PATH", "").split(os.pathsep)
    if venv_bin not in path_entries:
        os.environ["PATH"] = os.pathsep.join([venv_bin] + path_entries)


@functools.lru_cache(maxsize=None)
def build(name, *sources, extra_cuda_cflags=()):
    """Compile sources into an extension module, and return it.

        extension = build("s08_paged_attn", "app/cuda/s08_paged_attn.cu")
        extension.paged_attn(...)

    The paths are relative to the repo root. lru_cache keeps the result, so
    a call at every kernel launch is free after the first one.

    Call it INSIDE your wrapper function, not at import time. A kernel that
    does not compile must fail the check that uses it. It must not stop
    pytest from collecting the whole stage.
    """
    from torch.utils.cpp_extension import load

    _ninja_on_path()
    CACHE.mkdir(exist_ok=True)
    build_dir = CACHE / name
    build_dir.mkdir(exist_ok=True)

    paths = [str(ROOT / source) for source in sources]
    missing = [path for path in paths if not Path(path).exists()]
    if missing:
        raise FileNotFoundError(f"no such CUDA source: {', '.join(missing)}")

    _clear_stale_lock(build_dir)

    try:
        return load(
            name=name,
            sources=paths,
            build_directory=str(build_dir),
            extra_cuda_cflags=CFLAGS + arch_flags() + list(extra_cuda_cflags),
            verbose=bool(os.environ.get("VC_CUDA_VERBOSE")),
        )
    except Exception as error:
        raise RuntimeError(
            f"nvcc could not build {name} from {', '.join(sources)}.\n"
            f"Run it again with VC_CUDA_VERBOSE=1 to see the compiler output.\n"
            f"{error}"
        ) from None


# torch serializes the builds of one extension with a lock file. It polls for
# that lock for ever, and it prints nothing.
#
# Now stop a first compile with Ctrl-C, a killed test run or a closed
# notebook. The lock file stays after the process that made it, and every
# later run stops with no output.
#
# This repo only ever has one build of one extension, so a lock older than a
# long compile is certainly stale.
STALE_LOCK_SECONDS = 600


def _clear_stale_lock(build_dir):
    lock = Path(build_dir) / "lock"
    try:
        age = time.time() - lock.stat().st_mtime
    except FileNotFoundError:
        return
    if age > STALE_LOCK_SECONDS:
        print(f"cudalib: clearing a stale build lock in {build_dir} "
              f"({age / 60:.0f} minutes old). An earlier build was "
              f"interrupted.", file=sys.stderr)
        lock.unlink(missing_ok=True)
        (Path(build_dir) / ".ninja_lock").unlink(missing_ok=True)


def build_source(name, source):
    """Compile a CUDA source STRING, and return the module.

    The stage files are real .cu files, because that is how you write a
    kernel that you want to keep. In a notebook, where a kernel is three
    lines and the point is to see one number change, a string is easier.
    This function writes the source into the build cache and compiles it as
    a file, so the two paths behave the same.
    """
    CACHE.mkdir(exist_ok=True)
    source_path = CACHE / f"{name}.cu"
    if not source_path.exists() or source_path.read_text() != source:
        source_path.write_text(source)
    return build(name, str(source_path))


def module_path(name):
    """The .so that build() produced, for cuobjdump to read."""
    return CACHE / name / f"{name}.so"
