"""Provided: the helpers of the notebook "break it on purpose" of Part 6.

You do not edit this file. It gives you a fake engine that runs on the event
loop like the engine of stage 15, a client that records when each token
arrives, and a small simulation of users.
"""

import asyncio
import random
import time


class FakeEngine:
    """A continuous-batching engine with no GPU.

    Each step takes `step_ms` and gives one token to every running request.
    `slots` requests run at a time, and the others wait in a queue.
    """

    def __init__(self, slots=8, step_ms=22):
        self.slots, self.step = slots, step_ms / 1000
        self.waiting, self.running = [], {}
        self.generated = self.delivered = self.aborted = 0
        self.admitted_at = {}
        self.task = None

    def start(self):
        self.task = asyncio.get_running_loop().create_task(self._loop())

    async def stop(self):
        self.task.cancel()

    async def _loop(self):
        while True:
            while self.waiting and len(self.running) < self.slots:
                rid, queue, n = self.waiting.pop(0)
                self.running[rid] = [queue, n]
                self.admitted_at[rid] = time.perf_counter()
            await asyncio.sleep(self.step)                                # the GPU works
            for rid in list(self.running):
                queue, left = self.running[rid]
                queue.put_nowait(object())
                self.generated += 1
                self.running[rid][1] -= 1
                if left == 1:
                    queue.put_nowait(None)
                    del self.running[rid]

    async def generate(self, rid, tokens):
        """Yield `tokens` tokens. When the consumer stops, the request stays
        in the engine unless someone calls abort()."""
        queue = asyncio.Queue()
        self.waiting.append((rid, queue, tokens))
        while True:
            item = await queue.get()
            if item is None:
                return
            self.delivered += 1
            yield item

    def abort(self, rid):
        if rid in self.running:
            del self.running[rid]
            self.aborted += 1
        self.waiting = [w for w in self.waiting if w[0] != rid]


async def client(engine, rid, tokens, record, stop_after=None, on_close=None):
    """Consume a stream, and record the arrival time of each token."""
    start = time.perf_counter()
    times = []
    stream = engine.generate(rid, tokens)
    try:
        async for _ in stream:
            times.append(time.perf_counter() - start)
            if stop_after and len(times) >= stop_after:
                break                                                      # the user presses stop
    finally:
        await stream.aclose()
        if on_close:
            on_close(rid)
    record[rid] = times


def gaps(times):
    return [b - a for a, b in zip(times, times[1:])]


# ---------------------------------------------------------------- a simulation of users

def simulate_users(users, think_s, answer_tokens=200, slots=64, seconds=600, seed=0,
                   step_ms=lambda batch: 13 + 0.25 * batch):
    """Closed-loop users: each sends a request, reads the answer for
    `think_s` seconds (exponential), and sends the next one.
    Returns tokens/s, the mean number of running requests, and the mean
    time of one request."""
    rng = random.Random(seed)
    ready = [rng.uniform(0, think_s) if think_s else 0.0 for _ in range(users)]
    running, clock, tokens, busy, durations, started = [], 0.0, 0, 0.0, [], {}
    while clock < seconds:
        for user in range(users):
            if ready[user] is not None and ready[user] <= clock and len(running) < slots:
                running.append([user, answer_tokens])
                started[user] = clock
                ready[user] = None
        if not running:
            clock = min(r for r in ready if r is not None)
            continue
        step = step_ms(len(running)) / 1000
        clock += step
        busy += step * len(running)
        tokens += len(running)
        for request in running:
            request[1] -= 1
        for user, left in [r for r in running if r[1] == 0]:
            durations.append(clock - started[user])
            ready[user] = clock + (rng.expovariate(1 / think_s) if think_s else 0.0)
        running = [r for r in running if r[1] > 0]
    return tokens / clock, busy / clock, sum(durations) / len(durations)


def open_loop(rate, answer_tokens=200, slots=64, seconds=600, seed=0,
              step_ms=lambda batch: 13 + 0.25 * batch):
    """Requests arrive at `rate` per second, whatever happens.
    Returns tokens/s and the mean time from arrival to the last token."""
    rng = random.Random(seed)
    arrivals, t = [], 0.0
    while t < seconds:
        t += rng.expovariate(rate)
        arrivals.append(t)
    queue, running, clock, tokens, done = list(arrivals), [], 0.0, 0, []
    while (queue or running) and clock < seconds * 3:
        while queue and queue[0] <= clock and len(running) < slots:
            running.append([queue.pop(0), answer_tokens])
        if not running:
            clock = queue[0]
            continue
        clock += step_ms(len(running)) / 1000
        tokens += len(running)
        for request in running:
            request[1] -= 1
        done += [clock - a for a, left in running if left == 0]
        running = [r for r in running if r[1] > 0]
    return tokens / clock, sum(done) / len(done)
