"""Provided: the helpers of the notebook "break it on purpose" of Part 0.

You do not edit this file. It gives you a correct greedy loop, a way to put
your own attention function into the HF model, and a report of the first
token that differs.
"""

import math

import torch
import torch.nn.functional as F
from transformers import AttentionInterface


@torch.inference_mode()
def greedy_ids(model, token_ids, max_tokens, stop_ids=()):
    """A correct greedy loop with a KV cache. Returns the new token ids."""
    output = model(token_ids, use_cache=True)
    cache = output.past_key_values
    next_token = int(output.logits[0, -1].argmax())
    generated = []
    for _ in range(max_tokens):
        if next_token in stop_ids:
            break
        generated.append(next_token)
        output = model(torch.tensor([[next_token]], device=token_ids.device),
                       past_key_values=cache, use_cache=True)
        cache = output.past_key_values
        next_token = int(output.logits[0, -1].argmax())
    return generated


def greedy(model, tokenizer, prompt, max_tokens):
    device = next(model.parameters()).device
    token_ids = tokenizer(prompt, return_tensors='pt').input_ids.to(device)
    return greedy_ids(model, token_ids, max_tokens)


def first_difference(generated, expected):
    for position, (got, want) in enumerate(zip(generated, expected)):
        if got != want:
            return position
    if len(generated) != len(expected):
        return min(len(generated), len(expected))
    return None


def report(tokenizer, name, generated, expected):
    """Print the first token that differs from `expected`, and the text."""
    print(f'{name}: {len(generated)} tokens, first difference at: '
          f'{first_difference(generated, expected)}')
    print('  ', repr(tokenizer.decode(generated)))


def causal_bias(scores):
    """0 where a query may look, -inf where it may not.

    The queries are the LAST L positions of the S keys. In a prefill L = S.
    In a decode step L = 1, and the one query may see every key.
    """
    L, S = scores.shape[-2], scores.shape[-1]
    query_positions = torch.arange(S - L, S, device=scores.device)[:, None]
    key_positions = torch.arange(S, device=scores.device)[None, :]
    bias = torch.zeros(L, S, device=scores.device, dtype=scores.dtype)
    return bias.masked_fill(key_positions > query_positions, float('-inf'))


def correct_attention(q, k, v):
    """The reference: scaled, causal, and the softmax in float32."""
    scores = q @ k.transpose(-1, -2) / math.sqrt(q.shape[-1])
    scores = scores.float() + causal_bias(scores.float())
    return torch.softmax(scores, dim=-1).to(q.dtype) @ v


def use_attention(model, attention):
    """Make the model call `attention(q, k, v)` in every layer.

    q has shape (batch, heads, L, head_dim). k and v arrive with the same
    number of heads as q: this adapter repeats the KV heads for you. The
    function must return (batch, heads, L, head_dim). Pass None to go back to
    the attention of HF.
    """
    if attention is None:
        model.set_attn_implementation('sdpa')
        return

    def adapter(module, query, key, value, attention_mask, scaling=None, dropout=0.0, **kwargs):
        groups = query.shape[1] // key.shape[1]
        key = key.repeat_interleave(groups, dim=1)
        value = value.repeat_interleave(groups, dim=1)
        out = attention(query, key, value)
        return out.transpose(1, 2).contiguous(), None

    AttentionInterface.register('drill', adapter)
    model.set_attn_implementation('drill')


def sdpa_reference(q, k, v):
    return F.scaled_dot_product_attention(q, k, v, is_causal=q.shape[-2] > 1)
